sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_COVERAGE=true
    - php: 7
    - php: hhvm

install:
  - composer self-update
  - composer install
    
script:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then vendor/bin/phpunit --coverage-clover clover.xml; fi
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then vendor/bin/phpunit; fi
  
after_success:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then bash <(curl -s https://codecov.io/bash); fi
